import {
  AirVent,
  BatteryCharging,
  Blend,
  Boxes,
  Cable,
  Camera,
  Coffee,
  Cog,
  CookingPot,
  Droplet,
  Factory,
  Fan,
  Flame,
  Gamepad2,
  HeartPulse,
  Headphones,
  Laptop,
  Lightbulb,
  Microwave,
  Monitor,
  Printer,
  Refrigerator,
  Router,
  Scissors,
  Smartphone,
  Snowflake,
  Speaker,
  Tablet,
  Tv,
  WashingMachine,
  Watch,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  refrigerator: Refrigerator,
  television: Tv,
  tv: Tv,
  "air-conditioner": AirVent,
  ac: AirVent,
  fan: Fan,
  "washing-machine": WashingMachine,
  kitchen: Microwave,
  microwave: Microwave,
  mobile: Smartphone,
  smartphone: Smartphone,
  "mobile-phone": Smartphone,
  audio: Headphones,
  headphones: Headphones,
  "air-fryer": CookingPot,
  "sewing-machine": Scissors,
  laptop: Laptop,
  smartwatch: Watch,
  "power-bank": BatteryCharging,
  speaker: Speaker,
  // PDF-import batch (2026-10-06)
  tablet: Tablet,
  monitor: Monitor,
  printer: Printer,
  "wifi-router": Router,
  "gaming-console": Gamepad2,
  "deep-freezer": Snowflake,
  "microwave-oven": Microwave,
  "rice-cooker": CookingPot,
  "blender-mixer": Blend,
  "induction-cooker": Flame,
  "kettle-toaster-coffee": Coffee,
  "water-purifier": Droplet,
  "ceiling-fan": Fan,
  "rechargeable-fan": Fan,
  geyser: Flame,
  "iron-steamer": Wrench,
  "vacuum-cleaner": Wrench,
  "hair-dryer-straightener": Wrench,
  "trimmer-shaver": Wrench,
  "health-devices": HeartPulse,
  "led-light": Lightbulb,
  "ips-ups": BatteryCharging,
  "cctv-smart-home": Camera,
  "motors-drives-pumps": Cog,
  "switchgear-protection": Zap,
  "cables-installation": Cable,
  "power-generation-distribution": Zap,
  "automation-control": Cog,
  "test-measurement": Wrench,
  "industrial-lighting": Lightbulb,
  "heating-welding-process": Flame,
  "power-tools-workshop": Factory,
};

export function categoryIcon(slug: string): LucideIcon {
  return map[slug] ?? Boxes;
}
